#!/usr/bin/env python3
"""Generate roms_embedded.c: the recognised BIOS / patch ROMs in a
directory, or nothing at all.

The Master System BIOSes and the YM2413 patch ROM are copyrighted Sega and
Yamaha firmware and are not redistributed by this project (COMPLIANCE.md).
--none is therefore the SHIPPING configuration, not an error path: it emits
an empty table, and the machine boots the FujiNet cartridge directly.

With a directory (WITH_SMS_ROMS=ON, a developer build), every file in it
whose size and CRC-32 match MAME's table (core/src/roms.c) is embedded under
MAME's file name, whatever it is called locally. Anything else is ignored.

usage: embed-roms.py <out.c> <dir>
       embed-roms.py --none <out.c>
"""

import sys
import zlib
from pathlib import Path

# (size, crc) -> MAME's file name; mirrors s_bios[] in core/src/roms.c
KNOWN = {
    (0x2000, 0x0072ED54): "mpr-10052.rom",
    (0x20000, 0x91E93385): "mpr-11459a.rom",
    (0x20000, 0x8EDF7AC6): "mpr-11458.rom",
    (0x20000, 0xE79BB689): "missiled.rom",
    (0x2000, 0x72BEC693): "v1.0.bin",
    (0x2000, 0x1A15DFCC): "m404prot.rom",
    (0x2000, 0xB3D854F8): "mpr-10883.rom",
    (0x20000, 0xCF4A09EA): "mpr-12808.ic2",
    (0x40000, 0x81C3476B): "sonbios.rom",
    (0x2000, 0x48D44A13): "mpr-11124.ic2",
    (0x90, 0x6F582D01): "ym2413_instruments.bin",
}

HEADER = """/* Generated by tools/roms/embed-roms.py -- do not edit.
 * SPDX-License-Identifier: GPL-3.0-or-later
 */
#include "roms_embedded.h"

"""


def main():
    args = sys.argv[1:]
    if args and args[0] == "--none":
        if len(args) != 2:
            sys.exit(__doc__)
        Path(args[1]).write_text(
            HEADER
            + "/* Nothing embedded -- the shipping configuration. */\n"
            + "const sms_embedded_rom sms_embedded_roms[1] = { { 0, 0, 0 } };\n"
            + "const unsigned sms_embedded_rom_count = 0;\n")
        return 0

    if len(args) != 2:
        sys.exit(__doc__)
    out, src = Path(args[0]), Path(args[1])
    found = {}
    for f in sorted(src.iterdir()) if src.is_dir() else []:
        if not f.is_file() or f.stat().st_size > 0x40000:
            continue
        data = f.read_bytes()
        name = KNOWN.get((len(data), zlib.crc32(data) & 0xFFFFFFFF))
        if name and name not in found:
            found[name] = data

    body = [HEADER,
            "/* WITH_SMS_ROMS=ON: a developer build. NOT redistributable.\n"
            " * See COMPLIANCE.md. */\n"]
    for i, (name, data) in enumerate(found.items()):
        body.append("static const uint8_t rom%d[%d] = {\n" % (i, len(data)))
        for j in range(0, len(data), 16):
            body.append("    " + ",".join("0x%02X" % b for b in data[j:j + 16]) + ",\n")
        body.append("};\n")
    body.append("\nconst sms_embedded_rom sms_embedded_roms[%d] = {\n" % max(1, len(found)))
    for i, (name, data) in enumerate(found.items()):
        body.append('    { "%s", rom%d, %d },\n' % (name, i, len(data)))
    if not found:
        body.append("    { 0, 0, 0 },\n")
    body.append("};\nconst unsigned sms_embedded_rom_count = %d;\n" % len(found))
    out.write_text("".join(body))
    print("embed-roms: %d image(s): %s" % (len(found), ", ".join(found) or "none"))
    return 0


if __name__ == "__main__":
    sys.exit(main())
