#!/usr/bin/env python3
"""make_goldens.py -- capture MAME's answers to the timing probes.

Assembles each probe in tools/ab/probes (z88dk-z80asm), runs it on MAME's
own Master System with the FujiNet cartridge and no BIOS for every model
listed, dumps the 8K of work RAM after FRAMES frames, and writes
core/tests/probe_golden.h: the probe images and the RAM MAME left. The
vdp_timing test (core/tests/vdp_timing_test.c) then runs the same images on
the core and compares, so the calibration in core/sms/machine.c and vdp.c
(VDP_LAG, the SKEW_*, IRQ_AHEAD, BEAM_ROUND_MCLK) is checked on every build
with no MAME and no assembler.

    make_goldens.py [--mame ~/Workspace/mame] [--z88dk ~/Workspace/z88dk]

Re-run only when a probe changes. The smsj has no "none" BIOS in MAME, so
it is not captured (its I/O decode is covered by bios_synth instead).
"""

import argparse
import os
import subprocess
import sys
import tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(os.path.dirname(HERE))
PROBES = [("vhcount", 0x100, 0x700), ("irq", 0x000, 0x500)]
MODELS = ["sms1", "sms", "sms1pal", "smspal", "sg1000m3"]
FRAMES = 20


def assemble(z88dk, name, work):
    src = os.path.join(HERE, "probes", name + ".asm")
    out = os.path.join(work, name + ".bin")
    subprocess.run([os.path.join(z88dk, "bin", "z88dk-z80asm"), "-b", "-O" + work,
                    "-o=" + out, src], check=True)
    return open(out, "rb").read()


def mame_ram(mame, model, image, work):
    rom = os.path.join(work, "probe.sms")
    open(rom, "wb").write(image)
    ram = os.path.join(work, "ram.bin")
    args = ["./mame", model, "-bios", "none", "-skip_gameinfo", "-slot", "fujinet",
            "-cart", rom, "-snapshot_directory", os.path.join(work, "snap"),
            "-nvram_directory", os.path.join(work, "nvram"),
            "-cfg_directory", os.path.join(work, "cfg"),
            "-autoboot_script", os.path.join(HERE, "abshot.lua"),
            "-video", "none", "-sound", "none", "-nothrottle", "-seconds_to_run", "60"]
    if model == "sg1000m3":
        args[2:4] = []
    env = dict(os.environ, AB_FRAMES=str(FRAMES), AB_RAMDUMP=ram, FUJINET_TCP="127.0.0.1:1")
    subprocess.run(args, cwd=mame, env=env, check=True, capture_output=True)
    return open(ram, "rb").read()


def carray(name, data):
    lines = ["static const uint8_t %s[%d] = {" % (name, len(data))]
    for i in range(0, len(data), 16):
        lines.append("    " + ",".join("0x%02X" % b for b in data[i:i + 16]) + ",")
    lines.append("};")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--mame", default=os.path.expanduser("~/Workspace/mame"))
    ap.add_argument("--z88dk", default=os.path.expanduser("~/Workspace/z88dk"))
    o = ap.parse_args()

    out = ["/* probe_golden.h -- GENERATED by tools/ab/make_goldens.py from MAME; do not edit.",
           " * The timing probes (tools/ab/probes) and the work RAM MAME's own Master",
           " * System left after %d frames with no BIOS, per model. */" % FRAMES,
           "#ifndef PROBE_GOLDEN_H", "#define PROBE_GOLDEN_H", "#include <stdint.h>", "",
           "#define PROBE_FRAMES %d" % FRAMES, ""]
    table = []
    with tempfile.TemporaryDirectory() as work:
        for name, lo, hi in PROBES:
            img = assemble(o.z88dk, name, work)
            # Only the probe's code goes in the header: every probe is that
            # code, $FF to $7FF0, "TMR SEGA", zeros to 32K, and the test
            # rebuilds the image (probe_image() in vdp_timing_test.c).
            code = img[:0x7ff0].rstrip(b"\xff")
            assert img == code + b"\xff" * (0x7ff0 - len(code)) + b"TMR SEGA" + b"\x00" * 8, name
            out.append(carray("probe_%s" % name, code))
            for model in MODELS:
                ram = mame_ram(o.mame, model, img, work)
                out.append(carray("golden_%s_%s" % (name, model), ram[lo:hi]))
                table.append('    { "%s", "%s", probe_%s, sizeof probe_%s, 0x%04X, golden_%s_%s, sizeof golden_%s_%s },'
                             % (name, model, name, name, 0xC000 + lo, name, model, name, model))
                print("captured %s on %s" % (name, model))
    out += ["", "typedef struct {", "    const char *probe, *model;",
            "    const uint8_t *code; unsigned code_size;",
            "    uint16_t ram_addr; const uint8_t *ram; unsigned ram_size;",
            "} probe_golden_t;", "",
            "static const probe_golden_t probe_goldens[] = {"] + table + ["};", "", "#endif", ""]
    open(os.path.join(ROOT, "core", "tests", "probe_golden.h"), "w").write("\n".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main())
