# External source dependencies.
#
# Standard practice for every target in the FujiNet Go family: the build
# provides each dependency for itself. A plain `git clone` of this repository
# (no --recurse-submodules), GNOME Builder, a flatpak build or a source
# tarball all end up with a usable checkout without the developer having to
# know the dependency exists.
#
# One dependency (the emulator core is this repository's own C, transposed
# from MAME -- see core/sms/ and COMPLIANCE.md):
#
#   fujinet-firmware  Two things come from it. pico/sms is the FujiNet SMS
#                     cartridge firmware: its own fujimail/fujibus/smsmap/
#                     fuji_load sources, mailbox layout, loader page and the
#                     baked CONFIG client are staged verbatim into
#                     core/sms/fuji-generated by cmake/StageFujiProto.cmake,
#                     so the emulated cartridge and the hardware cannot
#                     disagree. Everything else is the RS232 PC runtime,
#                     built in-process as libfujinet by
#                     cmake/FujiNetRuntime.cmake. Pinned to the add-sms
#                     branch, which carries pico/sms on top of master
#                     (TCP_NODELAY on the BoIP socket included); the one
#                     thing the runtime needs on top -- .sms/.sg recognised
#                     as ROM images to push -- is tools/fujinet/patches/0002.
#
# Resolution order:
#   1. FUJINET_SRC (cache variable or environment) -- an out-of-tree working
#      checkout, which is how the cartridge and this app are developed in
#      tandem, e.g.
#          cmake -B build -DFUJINET_SRC=~/Workspace/fn-sms
#   2. third_party/<name>, initialising the submodule when this tree is a git
#      checkout and the path is a registered submodule.
#   3. Otherwise a direct clone of the pinned commit.

find_package(Git QUIET)

# fujinet-firmware, branch add-sms (b96613f36): the Sega Master System
# cartridge (pico/sms) with the Phantasy Star-style CONFIG baked in.
# Recorded in three places -- here and in both flatpak manifests
# (build-aux/flatpak/*.yml).
set(FUJINET_COMMIT "b96613f36de0f0f448c0be47b0069266f551766d")
set(FUJINET_URL "https://github.com/FujiNetWIFI/fujinet-firmware")

# sms_provide_dependency(NAME <n> PATH <p> SENTINEL <file> OVERRIDE <VAR>
#                           RESULT <out>
#                           [URL <u> COMMIT <sha>]        # git dependency
#                           [ARCHIVE <url> SHA256 <hash> [STRIP <dir>]])
#
# SENTINEL is a path inside the checkout that only exists once the sources are
# really there -- an empty submodule directory is otherwise indistinguishable
# from a populated one, and a half-extracted archive from a complete one.
function(sms_provide_dependency)
  cmake_parse_arguments(DEP ""
    "NAME;PATH;URL;COMMIT;ARCHIVE;SHA256;STRIP;SENTINEL;OVERRIDE;RESULT" ""
    ${ARGN})

  # 1. Explicit override: a checkout the developer maintains themselves.
  set(_override "")
  if(DEFINED ${DEP_OVERRIDE})
    set(_override "${${DEP_OVERRIDE}}")
  elseif(DEFINED ENV{${DEP_OVERRIDE}})
    set(_override "$ENV{${DEP_OVERRIDE}}")
  endif()
  if(_override)
    if(NOT EXISTS "${_override}/${DEP_SENTINEL}")
      message(FATAL_ERROR
        "${DEP_OVERRIDE}=${_override} does not look like a ${DEP_NAME} "
        "checkout (no ${DEP_SENTINEL}).")
    endif()
    message(STATUS "${DEP_NAME}: using ${_override} (${DEP_OVERRIDE})")
    set(${DEP_RESULT} "${_override}" PARENT_SCOPE)
    return()
  endif()

  set(_path "${CMAKE_SOURCE_DIR}/${DEP_PATH}")

  if(NOT EXISTS "${_path}/${DEP_SENTINEL}" AND DEP_ARCHIVE)
    # 2a. Archive dependency: download the pin and unpack it.
    #
    # Extract into a scratch directory first and move the result into place
    # only once it is complete, so an interrupted configure cannot leave a
    # partial tree that the sentinel test would go on to accept.
    set(_dl "${CMAKE_BINARY_DIR}/_deps/${DEP_NAME}.archive")
    set(_tmp "${CMAKE_BINARY_DIR}/_deps/${DEP_NAME}-extract")

    if(NOT EXISTS "${_dl}")
      message(STATUS "${DEP_NAME}: downloading ${DEP_ARCHIVE}")
      file(DOWNLOAD "${DEP_ARCHIVE}" "${_dl}"
           EXPECTED_HASH SHA256=${DEP_SHA256}
           TLS_VERIFY ON
           STATUS _dl_status)
      list(GET _dl_status 0 _dl_rc)
      if(NOT _dl_rc EQUAL 0)
        list(GET _dl_status 1 _dl_msg)
        file(REMOVE "${_dl}")
        message(FATAL_ERROR
          "Could not download ${DEP_NAME} from ${DEP_ARCHIVE}: ${_dl_msg}\n"
          "Download it by hand and unpack it, then point ${DEP_OVERRIDE} at "
          "the result.")
      endif()
    endif()

    file(REMOVE_RECURSE "${_tmp}")
    file(MAKE_DIRECTORY "${_tmp}")
    file(ARCHIVE_EXTRACT INPUT "${_dl}" DESTINATION "${_tmp}")

    set(_extracted "${_tmp}")
    if(DEP_STRIP)
      set(_extracted "${_tmp}/${DEP_STRIP}")
    endif()
    if(NOT EXISTS "${_extracted}/${DEP_SENTINEL}")
      message(FATAL_ERROR
        "${DEP_NAME} archive did not contain ${DEP_STRIP}/${DEP_SENTINEL} "
        "(${DEP_ARCHIVE}).")
    endif()

    file(REMOVE_RECURSE "${_path}")
    get_filename_component(_parent "${_path}" DIRECTORY)
    file(MAKE_DIRECTORY "${_parent}")
    file(RENAME "${_extracted}" "${_path}")
    file(REMOVE_RECURSE "${_tmp}")

  elseif(NOT EXISTS "${_path}/${DEP_SENTINEL}")
    find_package(Git QUIET)
    if(NOT GIT_FOUND)
      message(FATAL_ERROR
        "${DEP_NAME} is missing and git is not installed. Either install git "
        "or unpack ${DEP_URL} (commit ${DEP_COMMIT}) into ${DEP_PATH}.")
    endif()

    # 2b. Submodule checkout -- but ONLY when this path is actually a
    # registered submodule. Attempting it otherwise prints two lines of
    # "error: pathspec ... did not match any file(s) known to git" per
    # dependency on every fresh configure, and then silently falls through to
    # the clone below. The build was fine; the output said otherwise, which
    # is its own kind of bug.
    set(_is_submodule FALSE)
    if(EXISTS "${CMAKE_SOURCE_DIR}/.gitmodules")
      file(READ "${CMAKE_SOURCE_DIR}/.gitmodules" _gitmodules)
      string(FIND "${_gitmodules}" "path = ${DEP_PATH}" _found)
      if(NOT _found EQUAL -1)
        set(_is_submodule TRUE)
      endif()
    endif()

    if(_is_submodule AND EXISTS "${CMAKE_SOURCE_DIR}/.git")
      # --filter=blob:none keeps the fetch to the history the build needs;
      # fujinet-firmware is a large repository.
      message(STATUS "${DEP_NAME}: fetching submodule ${DEP_PATH}")
      execute_process(
        COMMAND ${GIT_EXECUTABLE} submodule update --init --filter=blob:none
                -- "${DEP_PATH}"
        WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
        RESULT_VARIABLE _rc)
      if(NOT _rc EQUAL 0)
        # Older servers/mirrors may refuse partial clones.
        execute_process(
          COMMAND ${GIT_EXECUTABLE} submodule update --init -- "${DEP_PATH}"
          WORKING_DIRECTORY "${CMAKE_SOURCE_DIR}"
          RESULT_VARIABLE _rc)
      endif()
    endif()

    if(NOT EXISTS "${_path}/${DEP_SENTINEL}")
      # 3. No git metadata (tarball): clone the pin outright.
      message(STATUS "${DEP_NAME}: cloning ${DEP_URL} @ ${DEP_COMMIT}")
      file(REMOVE_RECURSE "${_path}")
      execute_process(
        COMMAND ${GIT_EXECUTABLE} clone --filter=blob:none "${DEP_URL}" "${_path}"
        RESULT_VARIABLE _rc)
      if(_rc EQUAL 0)
        execute_process(
          COMMAND ${GIT_EXECUTABLE} -c advice.detachedHead=false checkout
                  --quiet "${DEP_COMMIT}"
          WORKING_DIRECTORY "${_path}"
          RESULT_VARIABLE _rc)
      endif()
    endif()
  endif()

  if(NOT EXISTS "${_path}/${DEP_SENTINEL}")
    if(DEP_ARCHIVE)
      message(FATAL_ERROR
        "Could not provide ${DEP_NAME}. Unpack ${DEP_ARCHIVE} into "
        "${DEP_PATH}, or point ${DEP_OVERRIDE} at an existing checkout.")
    else()
      message(FATAL_ERROR
        "Could not provide ${DEP_NAME}. Fetch it manually with\n"
        "    git submodule update --init ${DEP_PATH}\n"
        "or point ${DEP_OVERRIDE} at an existing checkout.")
    endif()
  endif()

  # Keep a git checkout on the pin recorded here. third_party/ is not a
  # submodule, so nothing else moves it when the pin is bumped, and a stale
  # tree fails to compile against the host code -- or worse, compiles and
  # silently changes the wire format the cart device speaks. A clean checkout
  # is moved to the pin (fetching it first if the clone predates it); one with
  # local changes stops the configure rather than have them overwritten.
  # Deliberate work on a different commit belongs behind ${DEP_OVERRIDE}.
  if(DEP_COMMIT AND EXISTS "${_path}/.git")
    find_package(Git QUIET)
    if(GIT_FOUND)
      execute_process(
        COMMAND ${GIT_EXECUTABLE} -C "${_path}" rev-parse HEAD
        OUTPUT_VARIABLE _head OUTPUT_STRIP_TRAILING_WHITESPACE
        ERROR_QUIET RESULT_VARIABLE _rc)
      if(_rc EQUAL 0 AND NOT _head STREQUAL DEP_COMMIT)
        execute_process(
          COMMAND ${GIT_EXECUTABLE} -C "${_path}" status --porcelain
                  --untracked-files=no
          OUTPUT_VARIABLE _dirty OUTPUT_STRIP_TRAILING_WHITESPACE
          ERROR_QUIET)
        if(_dirty)
          message(FATAL_ERROR
            "${DEP_NAME}: ${DEP_PATH} is at ${_head} with local changes, but "
            "cmake/Dependencies.cmake pins ${DEP_COMMIT}. Commit or stash "
            "them and re-run cmake to move to the pin, or keep working on "
            "this tree with -D${DEP_OVERRIDE}=${_path}.")
        endif()

        execute_process(
          COMMAND ${GIT_EXECUTABLE} -C "${_path}" cat-file -e
                  "${DEP_COMMIT}^{commit}"
          RESULT_VARIABLE _have ERROR_QUIET)
        if(NOT _have EQUAL 0)
          message(STATUS "${DEP_NAME}: fetching pinned ${DEP_COMMIT}")
          execute_process(
            COMMAND ${GIT_EXECUTABLE} -C "${_path}" fetch --quiet origin
            RESULT_VARIABLE _rc)
          execute_process(
            COMMAND ${GIT_EXECUTABLE} -C "${_path}" cat-file -e
                    "${DEP_COMMIT}^{commit}"
            RESULT_VARIABLE _have ERROR_QUIET)
          if(NOT _have EQUAL 0)
            # Servers that only advertise branch heads won't have served it
            # above if the pin's branch moved on; ask for the commit itself.
            execute_process(
              COMMAND ${GIT_EXECUTABLE} -C "${_path}" fetch --quiet origin
                      "${DEP_COMMIT}"
              RESULT_VARIABLE _have)
          endif()
          if(NOT _have EQUAL 0)
            message(FATAL_ERROR
              "${DEP_NAME}: pinned commit ${DEP_COMMIT} is not in ${DEP_PATH} "
              "and could not be fetched from origin. Fetch it by hand, or "
              "point ${DEP_OVERRIDE} at a checkout that has it.")
          endif()
        endif()

        message(STATUS "${DEP_NAME}: moving ${_head} -> pinned ${DEP_COMMIT}")
        execute_process(
          COMMAND ${GIT_EXECUTABLE} -C "${_path}" -c advice.detachedHead=false
                  checkout --quiet "${DEP_COMMIT}"
          RESULT_VARIABLE _rc)
        if(NOT _rc EQUAL 0)
          message(FATAL_ERROR
            "${DEP_NAME}: could not check out ${DEP_COMMIT} in ${DEP_PATH}.")
        endif()
      endif()
    endif()
  endif()

  message(STATUS "${DEP_NAME}: ${_path}")
  set(${DEP_RESULT} "${_path}" PARENT_SCOPE)
endfunction()
